#!/usr/bin/env python3
"""
Create complete Broadway show list from user-provided data (2010-2025).
"""

import pandas as pd
from pathlib import Path

# Complete list of shows from user
shows_text = """A BEHANDING IN SPOKANE
A FREE MAN OF COLOR
A LIFE IN THE THEATRE
A LITTLE NIGHT MUSIC
A VIEW FROM THE BRIDGE
ALL ABOUT ME
AMERICAN IDIOT
BLOODY BLOODY ANDREW JACKSON
BRIEF ENCOUNTER
BURN THE FLOOR
BYE BYE BIRDIE
CHICAGO
COLLECTED STORIES
COME FLY AWAY
DRIVING MISS DAISY
ELF
ELLING
ENRON
EVERYDAY RAPTURE
FELA!
FENCES
FINIAN'S RAINBOW
GOD OF CARNAGE
HAIR
IN THE HEIGHTS
IRVING BERLIN'S WHITE CHRISTMAS
JERSEY BOYS
LA BETE
LEND ME A TENOR
LOMBARDI
LOOPED
MAMMA MIA!
MARY POPPINS
MILLION DOLLAR QUARTET
MRS. WARREN'S PROFESSION
NEXT FALL
NEXT TO NORMAL
PRESENT LAUGHTER
RACE
RAGTIME
RED
ROCK OF AGES
SHREK THE MUSICAL
SONDHEIM ON SONDHEIM
SOUTH PACIFIC
SPIDER-MAN TURN OFF THE DARK
SUPERIOR DONUTS
THE 39 STEPS
THE ADDAMS FAMILY
THE IMPORTANCE OF BEING EARNEST
THE LION KING
THE MERCHANT OF VENICE
THE MIRACLE WORKER
THE PEE-WEE HERMAN SHOW
THE PHANTOM OF THE OPERA
THE PITMEN PAINTERS
THE SCOTTSBORO BOYS
TIME STANDS STILL
WICKED
WISHFUL DRINKING
WOMEN ON THE VERGE OF A NERVOUS BREAKDOWN
AN EVENING WITH PATTI LUPONE AND MANDY PATINKIN
ANYTHING GOES
ARCADIA
BABY IT'S YOU!
BORN YESTERDAY
CATCH ME IF YOU CAN
CHINGLISH
FOLLIES
GHETTO KLOWN
GODSPELL
GOOD PEOPLE
HIGH
HOW TO SUCCEED IN BUSINESS WITHOUT REALLY TRYING
JERUSALEM
KATHY GRIFFIN WANTS A TONY
LYSISTRATA JONES
MAN AND BOY
MASTER CLASS
ON A CLEAR DAY YOU CAN SEE FOREVER
OTHER DESERT CITIES
PORGY AND BESS
RELATIVELY SPEAKING
SEMINAR
SISTER ACT
STICK FLY
THAT CHAMPIONSHIP SEASON
THE BOOK OF MORMON
THE HOUSE OF BLUE LEAVES
THE MOTHERF**KER WITH THE HAT
THE MOUNTAINTOP
THE NORMAL HEART
THE PEOPLE IN THE PICTURE
THE ROAD TO MECCA
VENUS IN FUR
WAR HORSE
WONDERLAND
A STREETCAR NAMED DESIRE
AN ENEMY OF THE PEOPLE
ANNIE
CAT ON A HOT TIN ROOF
CHAPLIN
CLYBOURNE PARK
CYRANO DE BERGERAC
DEAD ACCOUNTS
DEATH OF A SALESMAN
DON'T DRESS FOR DINNER
END OF THE RAINBOW
EVITA
FRANKIE VALLI AND THE FOUR SEASONS ON BROADWAY
GLENGARRY GLEN ROSS
GOLDEN BOY
GORE VIDAL'S THE BEST MAN
GRACE
HARVEY
JESUS CHRIST SUPERSTAR
LEAP OF FAITH
MAGIC/BIRD
NEWSIES
NICE WORK IF YOU CAN GET IT
ONCE
ONE MAN, TWO GUVNORS
PETER AND THE STARCATCHER
PICNIC
PRIVATE LIVES
SCANDALOUS
SHATNER'S WORLD: WE JUST LIVE IN IT
THE ANARCHIST
THE COLUMNIST
THE HEIRESS
THE LYONS
THE MYSTERY OF EDWIN DROOD
THE OTHER PLACE
THE PERFORMERS
WHO'S AFRAID OF VIRGINIA WOOLF?
WIT
700 SUNDAYS
A GENTLEMAN'S GUIDE TO LOVE AND MURDER
A NIGHT WITH JANIS JOPLIN
A TIME TO KILL
AFTER MIDNIGHT
ANN
BETRAYAL
BIG FISH
BREAKFAST AT TIFFANY'S
CINDERELLA
FIRST DATE
FOREVER TANGO
HANDS ON A HARDBODY
I'LL EAT YOU LAST: A CHAT WITH SUE MENGERS
JEKYLL & HYDE
KINKY BOOTS
LET IT BE
LUCKY GUY
MACBETH
MACHINAL
MANILOW ON BROADWAY
MOTOWN THE MUSICAL
ORPHANS
PIPPIN
ROMEO AND JULIET
SOUL DOCTOR
THE ASSEMBLED PARTIES
THE BIG KNIFE
THE GLASS MENAGERIE
THE NANCE
THE RASCALS: ONCE UPON A DREAM
THE SNOW GEESE
THE TESTAMENT OF MARY
THE TRIP TO BOUNTIFUL
THE WINSLOW BOY
VANYA AND SONIA AND MASHA AND SPIKE
A DELICATE BALANCE
A RAISIN IN THE SUN
ACT ONE
ALADDIN
ALL THE WAY
BRONX BOMBERS
BULLETS OVER BROADWAY
CABARET
CASA VALENTINA
CONSTELLATIONS
DISGRACED
HEDWIG AND THE ANGRY INCH
HOLLER IF YA HEAR ME
HONEYMOON IN VEGAS
IF/THEN
IT'S ONLY A PLAY
LES MISÉRABLES
LOVE LETTERS
MOTHERS AND SONS
OF MICE AND MEN
ON THE TOWN
OUTSIDE MULLINGAR
ROCKY
SIDE SHOW
THE BRIDGES OF MADISON COUNTY
THE COUNTRY HOUSE
THE CRIPPLE OF INISHMAAN
THE CURIOUS INCIDENT OF THE DOG IN THE NIGHT-TIME
THE ELEPHANT MAN
THE LAST SHIP
THE REAL THING
THE REALISTIC JONESES
THE RIVER
THE VELOCITY OF AUTUMN
THIS IS OUR YOUTH
VIOLET
YOU CAN'T TAKE IT WITH YOU
AIRLINE HIGHWAY
ALLEGIANCE
AMAZING GRACE
AN ACT OF GOD
AN AMERICAN IN PARIS
CHINA DOLL
DAMES AT SEA
DOCTOR ZHIVAGO
FIDDLER ON THE ROOF
FINDING NEVERLAND
FISH IN THE DARK
FOOL FOR LOVE
FUN HOME
GIGI
HAMILTON
HAND TO GOD
IT SHOULDA BEEN YOU
KING CHARLES III
LIVING ON LOVE
LORD OF THE DANCE: DANGEROUS GAMES
MISERY
NOISES OFF
OLD TIMES
ON THE TWENTIETH CENTURY
PENN & TELLER ON BROADWAY
SCHOOL OF ROCK
SKYLIGHT
SOMETHING ROTTEN!
SPRING AWAKENING
SYLVIA
THE AUDIENCE
THE COLOR PURPLE
THE GIN GAME
THE HEIDI CHRONICLES
THE KING AND I
THE VISIT
THÉRÈSE RAQUIN
ALTON BROWN LIVE: EAT YOUR SCIENCE
AMERICAN PSYCHO
BLACK TO THE FUTURE
BLACKBIRD
BRIGHT STAR
CATS
DEAR EVAN HANSEN
DISASTER!
ECLIPSED
FALSETTOS
FULLY COMMITTED
HEISENBERG
HUGHIE
IN TRANSIT
LES LIAISONS DANGEREUSES
LONG DAY'S JOURNEY INTO NIGHT
OH, HELLO ON BROADWAY
OUR MOTHER'S BRIEF AFFAIR
SHE LOVES ME
THE CHERRY ORCHARD
THE CRUCIBLE
THE ENCOUNTER
THE FATHER
THE FRONT PAGE
THE HUMANS
THE PRESENT
TUCK EVERLASTING
WAITRESS
1984
A DOLL'S HOUSE, PART 2
AMÉLIE
ANASTASIA
BANDSTAND
CHARLIE AND THE CHOCOLATE FACTORY
COME FROM AWAY
FARINELLI AND THE KING
GROUNDHOG DAY
HELLO, DOLLY!
HOME FOR THE HOLIDAYS
INDECENT
JITNEY
JOHN LITHGOW: STORIES BY HEART
JUNK
LATIN HISTORY FOR MORONS
M. BUTTERFLY
MARVIN'S ROOM
METEOR SHOWER
MISS SAIGON
ONCE ON THIS ISLAND
OSLO
PRINCE OF BROADWAY
SIGNIFICANT OTHER
SIX DEGREES OF SEPARATION
SPONGEBOB SQUAREPANTS
SPRINGSTEEN ON BROADWAY
SUNDAY IN THE PARK WITH GEORGE
SUNSET BOULEVARD
SWEAT
THE BAND'S VISIT
THE CHILDREN
THE LITTLE FOXES
THE PARISIAN WOMAN
THE PLAY THAT GOES WRONG
THE PRICE
THE TERMS OF MY SURRENDER
TIME AND THE CONWAYS
WAR PAINT
AMERICAN SON
ANGELS IN AMERICA
BERNHARDT/HAMLET
CAROUSEL
CELEBRITY AUTOBIOGRAPHY
CHILDREN OF A LESSER GOD
CHOIR BOY
ESCAPE TO MARGARITAVILLE
FROZEN
GETTIN' THE BAND BACK TOGETHER
HEAD OVER HEELS
KING KONG
LOBBY HERO
MEAN GIRLS
MY FAIR LADY
NETWORK
ROCKTOPIA
SAINT JOAN
STRAIGHT WHITE MEN
THE BOYS IN THE BAND
THE CHER SHOW
THE FERRYMAN
THE ICEMAN COMETH
THE ILLUSIONISTS - MAGIC OF THE HOLIDAYS
THE LIFESPAN OF A FACT
THE NAP
THE PROM
THE WAVERLY GALLERY
THREE TALL WOMEN
TO KILL A MOCKINGBIRD
TORCH SONG
TRAVESTIES
TRUE WEST
A CHRISTMAS CAROL
A SOLDIER'S PLAY
AIN'T TOO PROUD
ALL MY SONS
AMERICAN UTOPIA
BE MORE CHILL
BEETLEJUICE
BURN THIS
DERREN BROWN: SECRET
FRANKIE AND JOHNNY IN THE CLAIR DE LUNE
FREESTYLE LOVE SUPREME
GARY: A SEQUEL TO TITUS ANDRONICUS
GRAND HORIZONS
HADESTOWN
HARRY CONNICK, JR. - A CELEBRATION OF COLE PORTER
HILLARY AND CLINTON
INK
JAGGED LITTLE PILL
KING LEAR
KISS ME, KATE
KRISTIN CHENOWETH: FOR THE GIRLS
LINDA VISTA
MOULIN ROUGE!
OKLAHOMA!
SLAVA'S SNOWSHOW
SLAVE PLAY
THE GREAT SOCIETY
THE HEIGHT OF THE STORM
THE INHERITANCE
THE ROSE TATTOO
THE SOUND INSIDE
TOOTSIE
WEST SIDE STORY
WHAT THE CONSTITUTION MEANS TO ME
YANNI
COMPANY
DIANA
GIRL FROM THE NORTH COUNTRY
HANGMEN
MY NAME IS LUCY BARTON
SIX: THE MUSICAL
THE LEHMAN TRILOGY
THE MINUTES
CAROLINE, OR CHANGE
CLYDE'S
FLYING OVER SUNSET
HARRY POTTER AND THE CURSED CHILD
IS THIS A ROOM
LACKAWANNA BLUES
MJ
MOULIN ROUGE! THE MUSICAL
MRS. DOUBTFIRE
PASS OVER
THE MUSIC MAN
THOUGHTS OF A COLORED MAN
TROUBLE IN MIND
& JULIET
1776
A BEAUTIFUL NOISE, THE NEIL DIAMOND MUSICAL
A STRANGE LOOP
AIN'T NO MO'
ALMOST FAMOUS
AMERICAN BUFFALO
BETWEEN RIVERSIDE AND CRAZY
BIRTHDAY CANDLES
COST OF LIVING
FOR COLORED GIRLS WHO HAVE CONSIDERED SUICIDE / WHEN THE RAINBOW IS ENUF
FUNNY GIRL
HOW I LEARNED TO DRIVE
INTO THE WOODS
KIMBERLY AKIMBO
KPOP
LEOPOLDSTADT
MR. SATURDAY NIGHT
OHIO STATE MURDERS
PARADISE SQUARE
PLAZA SUITE
SKELETON CREW
SOME LIKE IT HOT
TAKE ME OUT
THE COLLABORATION
THE KITE RUNNER
THE LITTLE PRINCE
THE PIANO LESSON
THE SKIN OF OUR TEETH
TOPDOG / UNDERDOG
A DOLL'S HOUSE
APPROPRIATE
BACK TO THE FUTURE: THE MUSICAL
BAD CINDERELLA
BOB FOSSE'S DANCIN'
CAMELOT
EL MAGO POP
FAT HAM
GOOD NIGHT, OSCAR
GREY HOUSE
GUTENBERG! THE MUSICAL!
HARMONY
HERE LIES LOVE
HOW TO DANCE IN OHIO
I NEED THAT
JAJA'S AFRICAN HAIR BRAIDING
LIFE OF PI
MELISSA ETHERIDGE: MY WINDOW
MERRILY WE ROLL ALONG
NEW YORK, NEW YORK
ONCE UPON A ONE MORE TIME
PARADE
PETER PAN GOES WRONG
PICTURES FROM HOME
PRAYER FOR THE FRENCH REPUBLIC
PRIMA FACIE
PURLIE VICTORIOUS: A NON-CONFEDERATE ROMP THROUGH THE COTTON PATCH
SHUCKED
SPAMALOT
SUMMER, 1976
SWEENEY TODD: THE DEMON BARBER OF FLEET STREET
THE COTTAGE
THE SHARK IS BROKEN
THE SIGN IN SIDNEY BRUSTEIN'S WINDOW
THE THANKSGIVING PLAY
A WONDERFUL WORLD: THE LOUIS ARMSTRONG MUSICAL
ALL IN: COMEDY ABOUT LOVE
CABARET AT THE KIT KAT CLUB
CULT OF LOVE
DAYS OF WINE AND ROSES
DEATH BECOMES HER
DOUBT: A PARABLE
EUREKA DAY
GYPSY
HELL'S KITCHEN
HOME
ILLINOISE
JOB
LEFT ON TENTH
LEMPICKA
MARY JANE
MAYBE HAPPY ENDING
MCNEAL
MOTHER PLAY
OH, MARY!
ONCE UPON A MATTRESS
OUR TOWN
PATRIOTS
ROMEO + JULIET
STEREOPHONIC
SUFFS
SUNSET BLVD.
SWEPT AWAY
TAMMY FAYE
THE GREAT GATSBY
THE HEART OF ROCK AND ROLL
THE HILLS OF CALIFORNIA
THE NOTEBOOK
THE OUTSIDERS
THE ROOMMATE
THE WHO'S TOMMY
THE WIZ
UNCLE VANYA
WATER FOR ELEPHANTS
YELLOW FACE
ART
BOOP! THE MUSICAL
BUENA VISTA SOCIAL CLUB
CALL ME IZZY
CHESS
DEAD OUTLAW
ENGLISH
FLOYD COLLINS
GOOD NIGHT, AND GOOD LUCK
JOHN PROCTOR IS THE VILLAIN
JUST IN TIME
LIBERATION
LITTLE BEAR RIDGE ROAD
OEDIPUS
OPERATION MINCEMEAT: A NEW MUSICAL
OTHELLO
PIRATES! THE PENZANCE MUSICAL
PUNCH
PURPOSE
REAL WOMEN HAVE CURVES: THE MUSICAL
REDWOOD
SMASH
STEPHEN SONDHEIM'S OLD FRIENDS
STRANGER THINGS: THE FIRST SHADOW
THE LAST FIVE YEARS
THE PICTURE OF DORIAN GRAY
THE QUEEN OF VERSAILLES
WAITING FOR GODOT"""

# Parse show names
shows = [line.strip() for line in shows_text.strip().split('\n') if line.strip()]

# Create DataFrame
df = pd.DataFrame({
    'show_id': range(1, len(shows) + 1),
    'show_name': shows
})

# Save to CSV
output_path = Path('raw/all_broadway_shows_2010_2025.csv')
output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(output_path, index=False)

print(f"✓ Created show list with {len(df)} shows")
print(f"  Saved to: {output_path}")
print(f"\nFirst 10 shows:")
print(df.head(10).to_string(index=False))
print(f"\nLast 10 shows:")
print(df.tail(10).to_string(index=False))
