"""
Meme candidate generator with strict constraints.

In production, this would call an LLM API. For now, implements
a rule-based generator that demonstrates the format and constraints.
"""

import json
import os
import random
from typing import Optional

from .io_schemas import LocalSnippet, MemeCandidate

# ============================================================================
# Generator Prompt Template
# ============================================================================

GENERATOR_PROMPT = """
You are a meme writer for queer Brooklyn nightlife (ages 20-40).

AUDIENCE: Queer folks who go out in Brooklyn; culturally literate; ages ~20-40
TONE: Witty, self-aware, lightly chaotic; slang-literate; no punching down
CONSTRAINTS:
- Must include a current local hook from provided snippets
- Output strictly as JSON with fields: visual_template, local_hook, tone, caption, rationale
- Caption MUST be ≤ 14 words (STRICT)
- No hashtags
- No venue doxxing (use "a venue in Bushwick" not specific names)
- No profanity stronger than PG-13
- Include evidence_refs field with snippet IDs used

VISUAL TEMPLATES (pick one):
- drake: Two-panel Drake meme (reject/prefer)
- distracted_boyfriend: Guy looking at another girl while girlfriend glares
- tweet_screenshot: Fake tweet with funny text
- two_panel: Before/After or This/That comparison
- top_text_bottom_text: Classic impact font meme

TONE OPTIONS:
- dry: Deadpan, understated humor
- slightly unhinged: Chaotic energy, maybe all caps
- coy: Playful, knowing wink

LOCAL HOOKS (must use from snippets):
- Borough/neighborhood specificity (Bushwick, Bed-Stuy, Ridgewood)
- Transit moments (L train, MTA delays, JMZ)
- Scene culture (cover charges, lines, dress codes, DIY spaces)
- Seasonal/temporal (coat check season, summer roof parties)

DEVICES:
- Exaggeration: "Getting to a Bushwick venue requires 3 trains and a pilgrimage"
- Misdirection: Setup expectation, subvert it
- Deadpan: State absurd thing matter-of-factly
- Code-switch: Mix highbrow/lowbrow or formal/slang
"""


# ============================================================================
# Rule-Based Generator (Demo Implementation)
# ============================================================================

# Template-specific caption structures
CAPTION_TEMPLATES = {
    "drake": [
        "{reject_thing}|{prefer_thing}",
    ],
    "distracted_boyfriend": [
        "boyfriend: {thing1}, girlfriend: {thing2}, other girl: {thing3}",
    ],
    "tweet_screenshot": [
        "{statement}",
    ],
    "two_panel": [
        "before: {before}|after: {after}",
        "them: {them}|me: {me}",
    ],
    "top_text_bottom_text": [
        "{top_text}|{bottom_text}",
    ],
}

# Example caption fragments (would be generated by LLM)
REJECT_PHRASES = [
    "taking the express train",
    "arriving on time",
    "venues with signage",
    "knowing the cross streets",
    "having exact change",
]

PREFER_PHRASES = [
    "getting lost in an industrial district for 40 minutes",
    "being fashionably late because the G train exists",
    "following a crowd of people in good outfits",
    "texting 'where even are you' at 11:47 PM",
    "Venmo-ing the door person",
]

BEFORE_PHRASES = [
    "texting 'omw' from bed",
    "saying you'll leave at 10",
    "checking the cover charge",
    "dressing for the weather",
]

AFTER_PHRASES = [
    "getting there at 1 AM",
    "leaving at 4 AM on a Tuesday",
    "paying $20 you don't have",
    "freezing in a crop top",
]

STATEMENTS = [
    "the L train sees you in your club outfit at 2 PM on Saturday and knows",
    "Brooklyn venue dress code: 'no sneakers' (everyone wearing sneakers)",
    "cover charge goes from $10 to $25 after you're already in line",
    "the only ATM is a Bitcoin machine",
    "you're not late the G train is just conceptual",
]


def _generate_caption_from_snippet(
    template: str,
    tone: str,
    snippet: LocalSnippet
) -> str:
    """
    Generate a caption using template and snippet.
    In production, this would call an LLM.
    """
    # Simple rule-based generation for demo
    if template == "drake":
        reject = random.choice(REJECT_PHRASES)
        prefer = f"{snippet.text[:40]}..."  # Use snippet
        parts = [reject, prefer]
        caption = " // ".join(parts)

    elif template == "two_panel":
        before = random.choice(BEFORE_PHRASES)
        after = snippet.text[:50]  # Use snippet
        caption = f"before: {before} // after: {after}"

    elif template == "tweet_screenshot":
        # Incorporate snippet into statement
        caption = f"{snippet.text[:80]}"

    elif template == "top_text_bottom_text":
        top = "brooklyn nightlife"
        bottom = snippet.text[:60]
        caption = f"{top} // {bottom}"

    else:  # distracted_boyfriend
        caption = f"me: existing // also me: {snippet.text[:60]}"

    # Ensure ≤ 14 words
    words = caption.split()
    if len(words) > 14:
        caption = " ".join(words[:14])

    return caption


def draft_candidates(
    snippets: list[LocalSnippet],
    n: int = 12,
    llm_api_key: Optional[str] = None
) -> list[MemeCandidate]:
    """
    Generate n meme candidates from retrieved snippets.

    Args:
        snippets: Retrieved local snippets for context
        n: Number of candidates to generate
        llm_api_key: Optional API key for LLM (stub for future)

    Returns:
        List of MemeCandidate objects
    """
    if not snippets:
        print("Warning: No snippets provided, generating generic candidates")
        snippets = [
            LocalSnippet(
                id="fallback_001",
                date="2025-11-05",
                source="manual",
                text="the L train at 2 AM on a Saturday",
                tags=["transit", "brooklyn"]
            )
        ]

    candidates = []
    templates = ["drake", "distracted_boyfriend", "tweet_screenshot", "two_panel", "top_text_bottom_text"]
    tones = ["dry", "slightly unhinged", "coy"]

    # TODO: Replace with actual LLM call
    # if llm_api_key:
    #     return _draft_with_llm(snippets, n, llm_api_key)

    for i in range(n):
        # Pick template and tone
        template = random.choice(templates)
        tone = random.choice(tones)

        # Pick snippet(s)
        snippet = random.choice(snippets)

        # Generate caption
        caption = _generate_caption_from_snippet(template, tone, snippet)

        # Extract local hook from snippet
        local_hook = snippet.text[:100]

        # Build candidate
        try:
            candidate = MemeCandidate(
                visual_template=template,
                local_hook=local_hook,
                tone=tone,
                caption=caption,
                rationale=f"Uses {snippet.source} snippet about {', '.join(snippet.tags[:2])}",
                evidence_refs=[snippet.id]
            )
            candidates.append(candidate)
        except ValueError as e:
            # Skip if validation fails (e.g., caption too long)
            print(f"Skipping candidate {i}: {e}")
            continue

    return candidates


def _draft_with_llm(
    snippets: list[LocalSnippet],
    n: int,
    api_key: str
) -> list[MemeCandidate]:
    """
    Draft candidates using LLM API.

    TODO: Implement with OpenAI/Anthropic/etc API
    """
    # Stub for future implementation
    # Would construct prompt with GENERATOR_PROMPT + snippets
    # Parse JSON responses into MemeCandidate objects
    raise NotImplementedError("LLM generation not yet implemented")


def validate_candidate(candidate: MemeCandidate) -> tuple[bool, Optional[str]]:
    """
    Validate a candidate meets all hard constraints.

    Returns:
        (is_valid, error_message)
    """
    # Check caption length
    word_count = len(candidate.caption.split())
    if word_count > 14:
        return False, f"Caption too long: {word_count} words (max 14)"

    # Check template is valid
    valid_templates = ["drake", "distracted_boyfriend", "tweet_screenshot", "two_panel", "top_text_bottom_text"]
    if candidate.visual_template not in valid_templates:
        return False, f"Invalid template: {candidate.visual_template}"

    # Check tone is valid
    valid_tones = ["dry", "slightly unhinged", "coy"]
    if candidate.tone not in valid_tones:
        return False, f"Invalid tone: {candidate.tone}"

    # Check has local hook
    if not candidate.local_hook or len(candidate.local_hook) < 5:
        return False, "Missing or too-short local_hook"

    return True, None
